/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Streaming Accounts */
        get: operations["list_streaming_accounts_api_streaming_accounts_get"];
        put?: never;
        /** Create Streaming Account */
        post: operations["create_streaming_account_api_streaming_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Streaming Playlists */
        get: operations["list_streaming_playlists_api_streaming_playlists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/playlists/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Streaming Playlist Config */
        get: operations["list_streaming_playlist_config_api_streaming_playlists_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Streaming Playlist */
        patch: operations["update_streaming_playlist_api_streaming_playlists__playlist_id__patch"];
        trace?: never;
    };
    "/api/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playlist Detail */
        get: operations["get_playlist_detail_api_playlists__playlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Playlist Tracks */
        get: operations["list_playlist_tracks_api_playlists__playlist_id__tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/tracks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Streaming Tracks */
        get: operations["search_streaming_tracks_api_streaming_tracks_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/tracks/{streaming_track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Streaming Track Detail */
        get: operations["get_streaming_track_detail_api_streaming_tracks__streaming_track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}/m3u": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Playlist M3U */
        get: operations["export_playlist_m3u_api_playlists__playlist_id__m3u_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/accounts/{account_id}/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Streaming Account Auth */
        patch: operations["update_streaming_account_auth_api_streaming_accounts__account_id__auth_patch"];
        trace?: never;
    };
    "/api/streaming/accounts/{account_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Streaming Account */
        post: operations["sync_streaming_account_api_streaming_accounts__account_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/accounts/{account_id}/refresh-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Streaming Account Metadata */
        post: operations["refresh_streaming_account_metadata_api_streaming_accounts__account_id__refresh_metadata_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/playlists/{playlist_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Streaming Playlist */
        post: operations["sync_streaming_playlist_api_streaming_playlists__playlist_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local-tracks/{local_track_id}/rematch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rematch Local Track */
        post: operations["rematch_local_track_api_local_tracks__local_track_id__rematch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local-tracks/{local_track_id}/rescue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescue Local Track Metadata */
        post: operations["rescue_local_track_metadata_api_local_tracks__local_track_id__rescue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Library Tracks */
        get: operations["list_library_tracks_api_library_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/missing-locally": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Missing Locally */
        get: operations["list_missing_locally_api_maintenance_missing_locally_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/unidentified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Unidentified */
        get: operations["list_unidentified_api_maintenance_unidentified_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/unidentified/{attempt_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Unidentified */
        post: operations["retry_unidentified_api_maintenance_unidentified__attempt_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/unidentified/{attempt_id}/ignore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ignore Unidentified */
        post: operations["ignore_unidentified_api_maintenance_unidentified__attempt_id__ignore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/unidentified/{attempt_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Unidentified */
        post: operations["restore_unidentified_api_maintenance_unidentified__attempt_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Proposal */
        post: operations["approve_proposal_api_proposals__proposal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Proposal */
        post: operations["reject_proposal_api_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/final-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Final Link */
        post: operations["create_final_link_api_final_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/final-links/{final_link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Break Final Link */
        delete: operations["break_final_link_api_final_links__final_link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/relationships/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Relationship Suggestions */
        get: operations["list_relationship_suggestions_api_streaming_relationships_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/relationships/suggestions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Relationship Suggestions */
        post: operations["generate_relationship_suggestions_api_streaming_relationships_suggestions_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/relationships/suggestions/{suggestion_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Relationship Suggestion */
        post: operations["accept_relationship_suggestion_api_streaming_relationships_suggestions__suggestion_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/relationships/suggestions/{suggestion_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Relationship Suggestion */
        post: operations["reject_relationship_suggestion_api_streaming_relationships_suggestions__suggestion_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Streaming Relationship */
        post: operations["create_streaming_relationship_api_streaming_relationships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/relationships/{relationship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Streaming Relationship */
        delete: operations["delete_streaming_relationship_api_streaming_relationships__relationship_id__delete"];
        options?: never;
        head?: never;
        /** Update Streaming Relationship */
        patch: operations["update_streaming_relationship_api_streaming_relationships__relationship_id__patch"];
        trace?: never;
    };
    "/api/local-tracks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Local Tracks */
        get: operations["search_local_tracks_api_local_tracks_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local-tracks/{local_track_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Local Track Audio */
        get: operations["get_local_track_audio_api_local_tracks__local_track_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local-tracks/{local_track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Local Track Detail */
        get: operations["get_local_track_detail_api_local_tracks__local_track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/general": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get General Settings */
        get: operations["get_general_settings_api_settings_general_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/ingest-folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Ingest Folder */
        post: operations["create_ingest_folder_api_settings_ingest_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/ingest-folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Ingest Folder */
        delete: operations["delete_ingest_folder_api_settings_ingest_folders__folder_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptStreamingRelationshipSuggestionRequest */
        AcceptStreamingRelationshipSuggestionRequest: {
            /** Relationship Type */
            relationship_type?: ("equivalent" | "related") | null;
            /** Winning Final Link Id */
            winning_final_link_id?: number | null;
        };
        /** AcceptStreamingRelationshipSuggestionResponse */
        AcceptStreamingRelationshipSuggestionResponse: {
            /** Suggestion Id */
            suggestion_id: number;
            /** Relationship Id */
            relationship_id: number;
            /**
             * Relationship Type
             * @enum {string}
             */
            relationship_type: "equivalent" | "related";
            /**
             * Status
             * @constant
             */
            status: "accepted";
            /** Accepted At */
            accepted_at: string;
            /** Detached Final Link Ids */
            detached_final_link_ids: number[];
        };
        /** BeetsAlbumDetailResponse */
        BeetsAlbumDetailResponse: {
            /** Beets Album Id */
            beets_album_id: number;
            /** Fields */
            fields: components["schemas"]["MetadataFieldResponse"][];
            /** Attributes */
            attributes: components["schemas"]["MetadataFieldResponse"][];
        };
        /** BeetsItemDetailResponse */
        BeetsItemDetailResponse: {
            /** Beets Id */
            beets_id: number;
            /** Fields */
            fields: components["schemas"]["MetadataFieldResponse"][];
            /** Attributes */
            attributes: components["schemas"]["MetadataFieldResponse"][];
        };
        /**
         * ConfidenceBand
         * @enum {string}
         */
        ConfidenceBand: "high" | "medium" | "low";
        /** CreateFinalLinkRequest */
        CreateFinalLinkRequest: {
            /** Local Track Id */
            local_track_id: number;
            /** Streaming Track Id */
            streaming_track_id: number;
            /** Replace Final Link Id */
            replace_final_link_id?: number | null;
            /**
             * Detach Conflicting Final Link Ids
             * @default []
             */
            detach_conflicting_final_link_ids: number[];
        };
        /** CreateFinalLinkResponse */
        CreateFinalLinkResponse: {
            /** Final Link Id */
            final_link_id: number;
            /** Local Track Id */
            local_track_id: number;
            /** Streaming Track Id */
            streaming_track_id: number;
            /** Approved At */
            approved_at: string;
            /** Status */
            status: string;
            /** Replaced Final Link Id */
            replaced_final_link_id: number | null;
            /** Detached Final Link Ids */
            detached_final_link_ids: number[];
        };
        /** CreateIngestFolderRequest */
        CreateIngestFolderRequest: {
            /** Path */
            path: string;
        };
        /** CreateStreamingAccountRequest */
        CreateStreamingAccountRequest: {
            /** Display Name */
            display_name: string;
            /** Browser Headers */
            browser_headers: {
                [key: string]: unknown;
            };
        };
        /** CreateStreamingRelationshipRequest */
        CreateStreamingRelationshipRequest: {
            /** First Track Id */
            first_track_id: number;
            /** Second Track Id */
            second_track_id: number;
            /**
             * Relationship Type
             * @enum {string}
             */
            relationship_type: "equivalent" | "related";
            /** Winning Final Link Id */
            winning_final_link_id?: number | null;
        };
        /** GeneralSettingsResponse */
        GeneralSettingsResponse: {
            /** Ingest Folders */
            ingest_folders: components["schemas"]["IngestFolderResponse"][];
        };
        /** GenerateStreamingRelationshipSuggestionsResponse */
        GenerateStreamingRelationshipSuggestionsResponse: {
            /** Created Count */
            created_count: number;
            /** Pruned Count */
            pruned_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** HealthzResponse */
        HealthzResponse: {
            /** Ok */
            ok: boolean;
            /** Database */
            database: string;
        };
        /** IngestFolderResponse */
        IngestFolderResponse: {
            /** Id */
            id: number;
            /** Path */
            path: string;
        };
        /** LibraryStatsResponse */
        LibraryStatsResponse: {
            /** Total */
            total: number;
            /** Linked */
            linked: number;
            /** Pending */
            pending: number;
            /** Unlinked */
            unlinked: number;
        };
        /** LibraryTrackResponse */
        LibraryTrackResponse: {
            /** Id */
            id: number;
            /** Final Link Id */
            final_link_id: number | null;
            /** Title */
            title: string;
            /** Artist */
            artist: string | null;
            /** Album */
            album: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** File Path */
            file_path: string;
            /** Library Root Rel Path */
            library_root_rel_path: string;
            /** Link Status */
            link_status: string;
            /** Match Method */
            match_method: string | null;
            /** File Status */
            file_status: string;
        };
        /** LibraryTracksResponse */
        LibraryTracksResponse: {
            stats: components["schemas"]["LibraryStatsResponse"];
            /** Tracks */
            tracks: components["schemas"]["LibraryTrackResponse"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** LocalTrackDetailResponse */
        LocalTrackDetailResponse: {
            /** Id */
            id: number;
            /** File Path */
            file_path: string;
            /** Library Root Rel Path */
            library_root_rel_path: string;
            /** Fingerprint */
            fingerprint: string | null;
            /** Beets Id */
            beets_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Link Status */
            link_status: string;
            /** Title */
            title: string | null;
            /** Artist */
            artist: string | null;
            /** Album */
            album: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            final_link: components["schemas"]["LocalTrackFinalLinkResponse"] | null;
            /** Pending Suggestions */
            pending_suggestions: components["schemas"]["LocalTrackSuggestionResponse"][];
            beets_item: components["schemas"]["BeetsItemDetailResponse"] | null;
            beets_album: components["schemas"]["BeetsAlbumDetailResponse"] | null;
            /** Failed Ingestion Attempts */
            failed_ingestion_attempts: components["schemas"]["LocalTrackFailedIngestionResponse"][];
        };
        /** LocalTrackFailedIngestionResponse */
        LocalTrackFailedIngestionResponse: {
            /** Id */
            id: number;
            /** Source Path */
            source_path: string;
            /** Filename */
            filename: string;
            /** Failure Reason */
            failure_reason: string;
            /**
             * Failed At
             * Format: date-time
             */
            failed_at: string;
        };
        /** LocalTrackFinalLinkResponse */
        LocalTrackFinalLinkResponse: {
            /** Id */
            id: number;
            /** Streaming Track Id */
            streaming_track_id: number;
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
            streaming_track: components["schemas"]["StreamingTrackSummaryResponse"];
        };
        /** LocalTrackSearchResponse */
        LocalTrackSearchResponse: {
            /** Tracks */
            tracks: components["schemas"]["LocalTrackSearchResultResponse"][];
        };
        /** LocalTrackSearchResultResponse */
        LocalTrackSearchResultResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /** Artist */
            artist: string | null;
            /** Album */
            album: string | null;
            /** File Path */
            file_path: string;
            /** Library Root Rel Path */
            library_root_rel_path: string;
            /** Link Status */
            link_status: string;
            /** Final Link Id */
            final_link_id: number | null;
        };
        /** LocalTrackSuggestionResponse */
        LocalTrackSuggestionResponse: {
            /** Id */
            id: number;
            /** Streaming Track Id */
            streaming_track_id: number;
            /** Match Method */
            match_method: string;
            /** Score */
            score: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            streaming_track: components["schemas"]["StreamingTrackSummaryResponse"];
        };
        /** MetadataFieldResponse */
        MetadataFieldResponse: {
            /** Key */
            key: string;
            /** Value */
            value: string | null;
        };
        /** MissingLocallyResponse */
        MissingLocallyResponse: {
            /** Tracks */
            tracks: components["schemas"]["MissingLocallyTrackResponse"][];
        };
        /** MissingLocallyTrackResponse */
        MissingLocallyTrackResponse: {
            /** Id */
            id: number;
            /** Provider Track Id */
            provider_track_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Playlist Count */
            playlist_count: number;
            /** Playlist Ids */
            playlist_ids: number[];
            /** Playlist Titles */
            playlist_titles: string[];
        };
        /** PlaylistDetail */
        PlaylistDetail: {
            /** Id */
            id: number;
            /** Account Id */
            account_id: number;
            /** Provider Playlist Id */
            provider_playlist_id: string;
            /** Name */
            name: string;
            /** Cover Art Url */
            cover_art_url: string | null;
            /**
             * Sync Mode
             * @enum {string}
             */
            sync_mode: "off" | "match_only" | "full";
            /** Provider Track Count */
            provider_track_count: number | null;
            /** Imported Track Count */
            imported_track_count: number;
            /** Linked Count */
            linked_count: number;
            /** Pending Count */
            pending_count: number;
            /** Unlinked Count */
            unlinked_count: number;
            /** Metadata Synced At */
            metadata_synced_at: string | null;
            /** Tracks Synced At */
            tracks_synced_at: string | null;
            /** Last Sync Error */
            last_sync_error: string | null;
            /** Last Sync Error At */
            last_sync_error_at: string | null;
        };
        /** PlaylistDetailResponse */
        PlaylistDetailResponse: {
            playlist: components["schemas"]["PlaylistDetail"];
        };
        /** PlaylistSyncResponse */
        PlaylistSyncResponse: {
            /** Playlist Id */
            playlist_id: number;
            /** Job Id */
            job_id: string;
        };
        /** PlaylistTrackResponse */
        PlaylistTrackResponse: {
            /** Id */
            id: number;
            /** Provider Track Id */
            provider_track_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Position */
            position: number;
            /** Status */
            status: string;
            /** Final Link Id */
            final_link_id: number | null;
            /** Local Track Id */
            local_track_id: number | null;
            /** Proposal Id */
            proposal_id: number | null;
        };
        /** PlaylistTracksResponse */
        PlaylistTracksResponse: {
            /** Tracks */
            tracks: components["schemas"]["PlaylistTrackResponse"][];
        };
        /** ProposalListResponse */
        ProposalListResponse: {
            /** Proposals */
            proposals: components["schemas"]["ProposalResponse"][];
            /** Total Count */
            total_count: number;
            /** Returned Count */
            returned_count: number;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ProposalResponse */
        ProposalResponse: {
            /** Id */
            id: number;
            /** Local Track Id */
            local_track_id: number;
            /** Local File Path */
            local_file_path: string;
            /** Local Title */
            local_title: string | null;
            /** Local Artist */
            local_artist: string | null;
            /** Local Album */
            local_album: string | null;
            /** Streaming Track Id */
            streaming_track_id: number;
            /** Streaming Provider Track Id */
            streaming_provider_track_id: string;
            /** Streaming Title */
            streaming_title: string;
            /** Streaming Artist */
            streaming_artist: string;
            /** Streaming Album */
            streaming_album: string | null;
            /** Match Method */
            match_method: string;
            /** Score */
            score: number;
            /** Status */
            status: string;
            confidence_band: components["schemas"]["ConfidenceBand"];
            /** Rejected At */
            rejected_at: string | null;
        };
        /** RejectStreamingRelationshipSuggestionResponse */
        RejectStreamingRelationshipSuggestionResponse: {
            /** Suggestion Id */
            suggestion_id: number;
            /**
             * Status
             * @constant
             */
            status: "rejected";
            /** Rejected At */
            rejected_at: string;
        };
        /** StreamingAccountResponse */
        StreamingAccountResponse: {
            /** Id */
            id: number;
            /** Provider */
            provider: string;
            /** Display Name */
            display_name: string;
            /** Auth State */
            auth_state: string;
            /** Auth Error */
            auth_error: string | null;
            /** Auth Error At */
            auth_error_at: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** StreamingAccountsResponse */
        StreamingAccountsResponse: {
            /** Accounts */
            accounts: components["schemas"]["StreamingAccountResponse"][];
        };
        /** StreamingPlaylistConfigListResponse */
        StreamingPlaylistConfigListResponse: {
            /** Playlists */
            playlists: components["schemas"]["StreamingPlaylistConfigResponse"][];
        };
        /** StreamingPlaylistConfigResponse */
        StreamingPlaylistConfigResponse: {
            /** Id */
            id: number;
            /** Account Id */
            account_id: number;
            /** Provider Playlist Id */
            provider_playlist_id: string;
            /** Title */
            title: string;
            /**
             * Sync Mode
             * @enum {string}
             */
            sync_mode: "off" | "match_only" | "full";
            /** Provider Track Count */
            provider_track_count: number | null;
            /** Imported Track Count */
            imported_track_count: number;
            /** Metadata Synced At */
            metadata_synced_at: string | null;
            /** Tracks Synced At */
            tracks_synced_at: string | null;
            /** Last Sync Error */
            last_sync_error: string | null;
            /** Last Sync Error At */
            last_sync_error_at: string | null;
        };
        /** StreamingPlaylistResponse */
        StreamingPlaylistResponse: {
            /** Id */
            id: number;
            /** Account Id */
            account_id: number;
            /** Provider Playlist Id */
            provider_playlist_id: string;
            /** Title */
            title: string;
            /**
             * Sync Mode
             * @enum {string}
             */
            sync_mode: "off" | "match_only" | "full";
            /** Provider Track Count */
            provider_track_count: number | null;
            /** Imported Track Count */
            imported_track_count: number;
            /** Metadata Synced At */
            metadata_synced_at: string | null;
            /** Tracks Synced At */
            tracks_synced_at: string | null;
            /** Last Sync Error */
            last_sync_error: string | null;
            /** Last Sync Error At */
            last_sync_error_at: string | null;
        };
        /** StreamingPlaylistsResponse */
        StreamingPlaylistsResponse: {
            /** Playlists */
            playlists: components["schemas"]["StreamingPlaylistResponse"][];
        };
        /** StreamingRelationshipConflictResponse */
        StreamingRelationshipConflictResponse: {
            /** First Group Track Ids */
            first_group_track_ids: number[];
            /** Second Group Track Ids */
            second_group_track_ids: number[];
            /** Local Track Ids */
            local_track_ids: number[];
            /** Final Links */
            final_links: components["schemas"]["StreamingRelationshipLocalLinkResponse"][];
        };
        /** StreamingRelationshipLocalLinkResponse */
        StreamingRelationshipLocalLinkResponse: {
            /** Final Link Id */
            final_link_id: number;
            /** Local Track Id */
            local_track_id: number;
            /** Local File Path */
            local_file_path: string | null;
            /** Local Title */
            local_title: string | null;
            /** Local Artist */
            local_artist: string | null;
            /** Local Album */
            local_album: string | null;
            /** Streaming Track Id */
            streaming_track_id: number;
            /** Source Streaming Track Id */
            source_streaming_track_id: number;
            /**
             * Resolution Source
             * @enum {string}
             */
            resolution_source: "direct" | "equivalent";
            /** Approved At */
            approved_at: string;
        };
        /** StreamingRelationshipMutationResponse */
        StreamingRelationshipMutationResponse: {
            /** Relationship Id */
            relationship_id: number;
            /**
             * Relationship Type
             * @enum {string}
             */
            relationship_type: "equivalent" | "related";
            /**
             * Status
             * @enum {string}
             */
            status: "created" | "updated" | "deleted";
            /** Accepted At */
            accepted_at: string | null;
            /** Detached Final Link Ids */
            detached_final_link_ids: number[];
        };
        /** StreamingRelationshipSuggestionListResponse */
        StreamingRelationshipSuggestionListResponse: {
            /** Suggestions */
            suggestions: components["schemas"]["StreamingRelationshipSuggestionResponse"][];
            /** Total Count */
            total_count: number;
            /** Returned Count */
            returned_count: number;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** StreamingRelationshipSuggestionResponse */
        StreamingRelationshipSuggestionResponse: {
            /** Id */
            id: number;
            /**
             * Relationship Type
             * @enum {string}
             */
            relationship_type: "equivalent" | "related";
            /** Match Method */
            match_method: string;
            /** Score */
            score: number;
            /** Confidence */
            confidence: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "accepted" | "rejected";
            /** Created At */
            created_at: string;
            first_track: components["schemas"]["StreamingRelationshipTrackResponse"];
            second_track: components["schemas"]["StreamingRelationshipTrackResponse"];
            first_link: components["schemas"]["StreamingRelationshipLocalLinkResponse"] | null;
            second_link: components["schemas"]["StreamingRelationshipLocalLinkResponse"] | null;
            /**
             * Conflict State
             * @enum {string}
             */
            conflict_state: "none" | "different_local_links";
            conflict: components["schemas"]["StreamingRelationshipConflictResponse"] | null;
        };
        /** StreamingRelationshipTrackResponse */
        StreamingRelationshipTrackResponse: {
            /** Id */
            id: number;
            /** Provider Track Id */
            provider_track_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album: string | null;
            /** Year */
            year: number | null;
            /** Isrc */
            isrc: string | null;
            /** Duration Ms */
            duration_ms: number | null;
        };
        /** StreamingSyncResponse */
        StreamingSyncResponse: {
            /** Account Id */
            account_id: number;
            /** Job Id */
            job_id: string;
        };
        /** StreamingTrackDetailResponse */
        StreamingTrackDetailResponse: {
            /** Id */
            id: number;
            /** Provider Track Id */
            provider_track_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album: string | null;
            /** Year */
            year: number | null;
            /** Isrc */
            isrc: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            resolved_local_link: components["schemas"]["StreamingTrackLocalLinkResponse"] | null;
            /** Equivalent Tracks */
            equivalent_tracks: components["schemas"]["StreamingTrackRelationshipPeerResponse"][];
            /** Relationships */
            relationships: components["schemas"]["StreamingTrackRelationshipResponse"][];
            /** Playlist Appearances */
            playlist_appearances: components["schemas"]["StreamingTrackPlaylistAppearanceResponse"][];
            /** Pending Local Suggestions */
            pending_local_suggestions: components["schemas"]["StreamingTrackPendingLocalSuggestionResponse"][];
        };
        /** StreamingTrackLocalLinkResponse */
        StreamingTrackLocalLinkResponse: {
            /** Final Link Id */
            final_link_id: number;
            /** Local Track Id */
            local_track_id: number;
            /** Source Streaming Track Id */
            source_streaming_track_id: number;
            /** Resolution Source */
            resolution_source: string;
            /** Approved At */
            approved_at: string;
            local_track: components["schemas"]["StreamingTrackLocalSummaryResponse"];
        };
        /** StreamingTrackLocalSummaryResponse */
        StreamingTrackLocalSummaryResponse: {
            /** Id */
            id: number;
            /** File Path */
            file_path: string;
            /** Library Root Rel Path */
            library_root_rel_path: string;
            /** Title */
            title: string | null;
            /** Artist */
            artist: string | null;
            /** Album */
            album: string | null;
        };
        /** StreamingTrackPendingLocalSuggestionResponse */
        StreamingTrackPendingLocalSuggestionResponse: {
            /** Id */
            id: number;
            /** Local Track Id */
            local_track_id: number;
            /** Match Method */
            match_method: string;
            /** Score */
            score: number;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            local_track: components["schemas"]["StreamingTrackLocalSummaryResponse"];
        };
        /** StreamingTrackPlaylistAppearanceResponse */
        StreamingTrackPlaylistAppearanceResponse: {
            /** Playlist Id */
            playlist_id: number;
            /** Account Id */
            account_id: number;
            /** Provider Playlist Id */
            provider_playlist_id: string;
            /** Title */
            title: string;
            /**
             * Sync Mode
             * @enum {string}
             */
            sync_mode: "off" | "match_only" | "full";
            /** Position */
            position: number;
        };
        /** StreamingTrackRelationshipPeerResponse */
        StreamingTrackRelationshipPeerResponse: {
            /** Id */
            id: number;
            /** Provider Track Id */
            provider_track_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album: string | null;
            /** Year */
            year: number | null;
            /** Isrc */
            isrc: string | null;
            /** Duration Ms */
            duration_ms: number | null;
        };
        /** StreamingTrackRelationshipResponse */
        StreamingTrackRelationshipResponse: {
            /** Id */
            id: number;
            /** Relationship Type */
            relationship_type: string;
            /** Accepted At */
            accepted_at: string;
            peer_track: components["schemas"]["StreamingTrackRelationshipPeerResponse"];
        };
        /** StreamingTrackSearchResponse */
        StreamingTrackSearchResponse: {
            /** Tracks */
            tracks: components["schemas"]["StreamingTrackSearchResultResponse"][];
        };
        /** StreamingTrackSearchResultResponse */
        StreamingTrackSearchResultResponse: {
            /** Id */
            id: number;
            /** Provider Track Id */
            provider_track_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album: string | null;
            /** Year */
            year: number | null;
            /** Isrc */
            isrc: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Link Status */
            link_status: string;
            /** Final Link Id */
            final_link_id: number | null;
            /** Local Track Id */
            local_track_id: number | null;
        };
        /** StreamingTrackSummaryResponse */
        StreamingTrackSummaryResponse: {
            /** Id */
            id: number;
            /** Provider Track Id */
            provider_track_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album: string | null;
            /** Year */
            year: number | null;
            /** Isrc */
            isrc: string | null;
            /** Duration Ms */
            duration_ms: number | null;
        };
        /** UnidentifiedIgnoreResponse */
        UnidentifiedIgnoreResponse: {
            /** Id */
            id: number;
            /** Ignored At */
            ignored_at: string;
            /** Source Path */
            source_path: string;
        };
        /** UnidentifiedResponse */
        UnidentifiedResponse: {
            /** Tracks */
            tracks: components["schemas"]["UnidentifiedTrackResponse"][];
        };
        /** UnidentifiedRestoreResponse */
        UnidentifiedRestoreResponse: {
            /** Id */
            id: number;
            /** Ignored At */
            ignored_at: null;
            /** Source Path */
            source_path: string;
        };
        /** UnidentifiedRetryResponse */
        UnidentifiedRetryResponse: {
            /** Id */
            id: number;
            /** Job Id */
            job_id: string | null;
            /** Source Path */
            source_path: string;
        };
        /** UnidentifiedTrackResponse */
        UnidentifiedTrackResponse: {
            /** Id */
            id: number;
            /** Attempt Count */
            attempt_count: number;
            /** Can Rematch Local Track */
            can_rematch_local_track: boolean;
            /** Can Rescue Metadata */
            can_rescue_metadata: boolean;
            /** Failed At */
            failed_at: string;
            /** Failure Reason */
            failure_reason: string;
            /** Filename */
            filename: string;
            /** First Failed At */
            first_failed_at: string;
            /** Ignored At */
            ignored_at: string | null;
            /** Local Track Id */
            local_track_id: number | null;
            /** Source Mtime Ns */
            source_mtime_ns: number | null;
            /** Source Path */
            source_path: string;
            /** Source Size */
            source_size: number | null;
        };
        /** UpdateStreamingAccountAuthRequest */
        UpdateStreamingAccountAuthRequest: {
            /** Browser Headers */
            browser_headers: {
                [key: string]: unknown;
            };
        };
        /** UpdateStreamingPlaylistRequest */
        UpdateStreamingPlaylistRequest: {
            /**
             * Sync Mode
             * @enum {string}
             */
            sync_mode: "off" | "match_only" | "full";
        };
        /** UpdateStreamingRelationshipRequest */
        UpdateStreamingRelationshipRequest: {
            /**
             * Relationship Type
             * @enum {string}
             */
            relationship_type: "equivalent" | "related";
            /** Winning Final Link Id */
            winning_final_link_id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_streaming_accounts_api_streaming_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingAccountsResponse"];
                };
            };
        };
    };
    create_streaming_account_api_streaming_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStreamingAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_streaming_playlists_api_streaming_playlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingPlaylistsResponse"];
                };
            };
        };
    };
    list_streaming_playlist_config_api_streaming_playlists_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingPlaylistConfigListResponse"];
                };
            };
        };
    };
    update_streaming_playlist_api_streaming_playlists__playlist_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStreamingPlaylistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingPlaylistConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playlist_detail_api_playlists__playlist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_playlist_tracks_api_playlists__playlist_id__tracks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistTracksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_streaming_tracks_api_streaming_tracks_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingTrackSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_streaming_track_detail_api_streaming_tracks__streaming_track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                streaming_track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingTrackDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_playlist_m3u_api_playlists__playlist_id__m3u_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_streaming_account_auth_api_streaming_accounts__account_id__auth_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStreamingAccountAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_streaming_account_api_streaming_accounts__account_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_streaming_account_metadata_api_streaming_accounts__account_id__refresh_metadata_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_streaming_playlist_api_streaming_playlists__playlist_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rematch_local_track_api_local_tracks__local_track_id__rematch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                local_track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescue_local_track_metadata_api_local_tracks__local_track_id__rescue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                local_track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_library_tracks_api_library_tracks_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryTracksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_missing_locally_api_maintenance_missing_locally_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingLocallyResponse"];
                };
            };
        };
    };
    list_unidentified_api_maintenance_unidentified_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidentifiedResponse"];
                };
            };
        };
    };
    retry_unidentified_api_maintenance_unidentified__attempt_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidentifiedRetryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ignore_unidentified_api_maintenance_unidentified__attempt_id__ignore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidentifiedIgnoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_unidentified_api_maintenance_unidentified__attempt_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidentifiedRestoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_proposals_get: {
        parameters: {
            query?: {
                band?: components["schemas"]["ConfidenceBand"] | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_proposal_api_proposals__proposal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_api_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_final_link_api_final_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFinalLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFinalLinkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    break_final_link_api_final_links__final_link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                final_link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_relationship_suggestions_api_streaming_relationships_suggestions_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                relationship_type?: ("equivalent" | "related") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingRelationshipSuggestionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_relationship_suggestions_api_streaming_relationships_suggestions_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateStreamingRelationshipSuggestionsResponse"];
                };
            };
        };
    };
    accept_relationship_suggestion_api_streaming_relationships_suggestions__suggestion_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AcceptStreamingRelationshipSuggestionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptStreamingRelationshipSuggestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_relationship_suggestion_api_streaming_relationships_suggestions__suggestion_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectStreamingRelationshipSuggestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_streaming_relationship_api_streaming_relationships_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStreamingRelationshipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingRelationshipMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_streaming_relationship_api_streaming_relationships__relationship_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relationship_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingRelationshipMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_streaming_relationship_api_streaming_relationships__relationship_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relationship_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStreamingRelationshipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingRelationshipMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_local_tracks_api_local_tracks_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalTrackSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_local_track_audio_api_local_tracks__local_track_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                local_track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_local_track_detail_api_local_tracks__local_track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                local_track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalTrackDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_general_settings_api_settings_general_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneralSettingsResponse"];
                };
            };
        };
    };
    create_ingest_folder_api_settings_ingest_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIngestFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestFolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ingest_folder_api_settings_ingest_folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
