/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Streaming Accounts */
        get: operations["list_streaming_accounts_api_streaming_accounts_get"];
        put?: never;
        /** Create Streaming Account */
        post: operations["create_streaming_account_api_streaming_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Streaming Playlists */
        get: operations["list_streaming_playlists_api_streaming_playlists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/playlists/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Streaming Playlist Config */
        get: operations["list_streaming_playlist_config_api_streaming_playlists_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Streaming Playlist */
        patch: operations["update_streaming_playlist_api_streaming_playlists__playlist_id__patch"];
        trace?: never;
    };
    "/api/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playlist Detail */
        get: operations["get_playlist_detail_api_playlists__playlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Playlist Tracks */
        get: operations["list_playlist_tracks_api_playlists__playlist_id__tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}/m3u": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Playlist M3U */
        get: operations["export_playlist_m3u_api_playlists__playlist_id__m3u_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/accounts/{account_id}/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Streaming Account Auth */
        patch: operations["update_streaming_account_auth_api_streaming_accounts__account_id__auth_patch"];
        trace?: never;
    };
    "/api/streaming/accounts/{account_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Streaming Account */
        post: operations["sync_streaming_account_api_streaming_accounts__account_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/accounts/{account_id}/refresh-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Streaming Account Metadata */
        post: operations["refresh_streaming_account_metadata_api_streaming_accounts__account_id__refresh_metadata_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming/playlists/{playlist_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Streaming Playlist */
        post: operations["sync_streaming_playlist_api_streaming_playlists__playlist_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local-tracks/{local_track_id}/rematch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rematch Local Track */
        post: operations["rematch_local_track_api_local_tracks__local_track_id__rematch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local-tracks/{local_track_id}/rescue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescue Local Track Metadata */
        post: operations["rescue_local_track_metadata_api_local_tracks__local_track_id__rescue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Library Tracks */
        get: operations["list_library_tracks_api_library_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/missing-locally": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Missing Locally */
        get: operations["list_missing_locally_api_maintenance_missing_locally_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/unidentified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Unidentified */
        get: operations["list_unidentified_api_maintenance_unidentified_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Proposal */
        post: operations["approve_proposal_api_proposals__proposal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Proposal */
        post: operations["reject_proposal_api_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/final-links/{final_link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Break Final Link */
        delete: operations["break_final_link_api_final_links__final_link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local-tracks/{local_track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Local Track Detail */
        get: operations["get_local_track_detail_api_local_tracks__local_track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/general": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get General Settings */
        get: operations["get_general_settings_api_settings_general_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/ingest-folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Ingest Folder */
        post: operations["create_ingest_folder_api_settings_ingest_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/ingest-folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Ingest Folder */
        delete: operations["delete_ingest_folder_api_settings_ingest_folders__folder_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConfidenceBand
         * @enum {string}
         */
        ConfidenceBand: "high" | "medium" | "low";
        /** CreateIngestFolderRequest */
        CreateIngestFolderRequest: {
            /** Path */
            path: string;
        };
        /** CreateStreamingAccountRequest */
        CreateStreamingAccountRequest: {
            /** Display Name */
            display_name: string;
            /** Browser Headers */
            browser_headers: {
                [key: string]: unknown;
            };
        };
        /** GeneralSettingsResponse */
        GeneralSettingsResponse: {
            /** Ingest Folders */
            ingest_folders: components["schemas"]["IngestFolderResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** HealthzResponse */
        HealthzResponse: {
            /** Ok */
            ok: boolean;
            /** Database */
            database: string;
        };
        /** IngestFolderResponse */
        IngestFolderResponse: {
            /** Id */
            id: number;
            /** Path */
            path: string;
        };
        /** LibraryStatsResponse */
        LibraryStatsResponse: {
            /** Total */
            total: number;
            /** Linked */
            linked: number;
            /** Pending */
            pending: number;
            /** Unlinked */
            unlinked: number;
        };
        /** LibraryTrackResponse */
        LibraryTrackResponse: {
            /** Id */
            id: number;
            /** Final Link Id */
            final_link_id: number | null;
            /** Title */
            title: string;
            /** Artist */
            artist: string | null;
            /** Album */
            album: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** File Path */
            file_path: string;
            /** Library Root Rel Path */
            library_root_rel_path: string;
            /** Link Status */
            link_status: string;
            /** Match Method */
            match_method: string | null;
            /** File Status */
            file_status: string;
        };
        /** LibraryTracksResponse */
        LibraryTracksResponse: {
            stats: components["schemas"]["LibraryStatsResponse"];
            /** Tracks */
            tracks: components["schemas"]["LibraryTrackResponse"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** LocalTrackDetailResponse */
        LocalTrackDetailResponse: {
            /** Id */
            id: number;
            /** File Path */
            file_path: string;
            /** Library Root Rel Path */
            library_root_rel_path: string;
            /** Link Status */
            link_status: string;
            final_link: components["schemas"]["LocalTrackFinalLinkResponse"] | null;
            /** Pending Suggestions */
            pending_suggestions: components["schemas"]["LocalTrackSuggestionResponse"][];
            /** Failed Ingestion Attempts */
            failed_ingestion_attempts: components["schemas"]["LocalTrackFailedIngestionResponse"][];
        };
        /** LocalTrackFailedIngestionResponse */
        LocalTrackFailedIngestionResponse: {
            /** Id */
            id: number;
            /** Source Path */
            source_path: string;
            /** Filename */
            filename: string;
            /** Failure Reason */
            failure_reason: string;
            /**
             * Failed At
             * Format: date-time
             */
            failed_at: string;
        };
        /** LocalTrackFinalLinkResponse */
        LocalTrackFinalLinkResponse: {
            /** Id */
            id: number;
            /** Streaming Track Id */
            streaming_track_id: number;
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
        };
        /** LocalTrackSuggestionResponse */
        LocalTrackSuggestionResponse: {
            /** Id */
            id: number;
            /** Streaming Track Id */
            streaming_track_id: number;
            /** Match Method */
            match_method: string;
            /** Score */
            score: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MissingLocallyResponse */
        MissingLocallyResponse: {
            /** Tracks */
            tracks: components["schemas"]["MissingLocallyTrackResponse"][];
        };
        /** MissingLocallyTrackResponse */
        MissingLocallyTrackResponse: {
            /** Id */
            id: number;
            /** Provider Track Id */
            provider_track_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Playlist Count */
            playlist_count: number;
            /** Playlist Ids */
            playlist_ids: number[];
            /** Playlist Titles */
            playlist_titles: string[];
        };
        /** PlaylistDetail */
        PlaylistDetail: {
            /** Id */
            id: number;
            /** Account Id */
            account_id: number;
            /** Provider Playlist Id */
            provider_playlist_id: string;
            /** Name */
            name: string;
            /** Cover Art Url */
            cover_art_url: string | null;
            /**
             * Sync Mode
             * @enum {string}
             */
            sync_mode: "off" | "match_only" | "full";
            /** Provider Track Count */
            provider_track_count: number | null;
            /** Imported Track Count */
            imported_track_count: number;
            /** Linked Count */
            linked_count: number;
            /** Pending Count */
            pending_count: number;
            /** Unlinked Count */
            unlinked_count: number;
            /** Metadata Synced At */
            metadata_synced_at: string | null;
            /** Tracks Synced At */
            tracks_synced_at: string | null;
            /** Last Sync Error */
            last_sync_error: string | null;
            /** Last Sync Error At */
            last_sync_error_at: string | null;
        };
        /** PlaylistDetailResponse */
        PlaylistDetailResponse: {
            playlist: components["schemas"]["PlaylistDetail"];
        };
        /** PlaylistSyncResponse */
        PlaylistSyncResponse: {
            /** Playlist Id */
            playlist_id: number;
            /** Job Id */
            job_id: string;
        };
        /** PlaylistTrackResponse */
        PlaylistTrackResponse: {
            /** Id */
            id: number;
            /** Provider Track Id */
            provider_track_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Position */
            position: number;
            /** Status */
            status: string;
            /** Final Link Id */
            final_link_id: number | null;
            /** Local Track Id */
            local_track_id: number | null;
            /** Proposal Id */
            proposal_id: number | null;
        };
        /** PlaylistTracksResponse */
        PlaylistTracksResponse: {
            /** Tracks */
            tracks: components["schemas"]["PlaylistTrackResponse"][];
        };
        /** ProposalListResponse */
        ProposalListResponse: {
            /** Proposals */
            proposals: components["schemas"]["ProposalResponse"][];
        };
        /** ProposalResponse */
        ProposalResponse: {
            /** Id */
            id: number;
            /** Local Track Id */
            local_track_id: number;
            /** Local File Path */
            local_file_path: string;
            /** Local Title */
            local_title: string | null;
            /** Local Artist */
            local_artist: string | null;
            /** Local Album */
            local_album: string | null;
            /** Streaming Track Id */
            streaming_track_id: number;
            /** Streaming Title */
            streaming_title: string;
            /** Streaming Artist */
            streaming_artist: string;
            /** Streaming Album */
            streaming_album: string | null;
            /** Match Method */
            match_method: string;
            /** Score */
            score: number;
            /** Status */
            status: string;
            confidence_band: components["schemas"]["ConfidenceBand"];
            /** Rejected At */
            rejected_at: string | null;
        };
        /** StreamingAccountResponse */
        StreamingAccountResponse: {
            /** Id */
            id: number;
            /** Provider */
            provider: string;
            /** Display Name */
            display_name: string;
            /** Auth State */
            auth_state: string;
            /** Auth Error */
            auth_error: string | null;
            /** Auth Error At */
            auth_error_at: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** StreamingAccountsResponse */
        StreamingAccountsResponse: {
            /** Accounts */
            accounts: components["schemas"]["StreamingAccountResponse"][];
        };
        /** StreamingPlaylistConfigListResponse */
        StreamingPlaylistConfigListResponse: {
            /** Playlists */
            playlists: components["schemas"]["StreamingPlaylistConfigResponse"][];
        };
        /** StreamingPlaylistConfigResponse */
        StreamingPlaylistConfigResponse: {
            /** Id */
            id: number;
            /** Account Id */
            account_id: number;
            /** Provider Playlist Id */
            provider_playlist_id: string;
            /** Title */
            title: string;
            /**
             * Sync Mode
             * @enum {string}
             */
            sync_mode: "off" | "match_only" | "full";
            /** Provider Track Count */
            provider_track_count: number | null;
            /** Imported Track Count */
            imported_track_count: number;
            /** Metadata Synced At */
            metadata_synced_at: string | null;
            /** Tracks Synced At */
            tracks_synced_at: string | null;
            /** Last Sync Error */
            last_sync_error: string | null;
            /** Last Sync Error At */
            last_sync_error_at: string | null;
        };
        /** StreamingPlaylistResponse */
        StreamingPlaylistResponse: {
            /** Id */
            id: number;
            /** Account Id */
            account_id: number;
            /** Provider Playlist Id */
            provider_playlist_id: string;
            /** Title */
            title: string;
            /**
             * Sync Mode
             * @enum {string}
             */
            sync_mode: "off" | "match_only" | "full";
            /** Provider Track Count */
            provider_track_count: number | null;
            /** Imported Track Count */
            imported_track_count: number;
            /** Metadata Synced At */
            metadata_synced_at: string | null;
            /** Tracks Synced At */
            tracks_synced_at: string | null;
            /** Last Sync Error */
            last_sync_error: string | null;
            /** Last Sync Error At */
            last_sync_error_at: string | null;
        };
        /** StreamingPlaylistsResponse */
        StreamingPlaylistsResponse: {
            /** Playlists */
            playlists: components["schemas"]["StreamingPlaylistResponse"][];
        };
        /** StreamingSyncResponse */
        StreamingSyncResponse: {
            /** Account Id */
            account_id: number;
            /** Job Id */
            job_id: string;
        };
        /** UnidentifiedResponse */
        UnidentifiedResponse: {
            /** Tracks */
            tracks: components["schemas"]["UnidentifiedTrackResponse"][];
        };
        /** UnidentifiedTrackResponse */
        UnidentifiedTrackResponse: {
            /** Id */
            id: number;
            /** Failed At */
            failed_at: string;
            /** Failure Reason */
            failure_reason: string;
            /** Filename */
            filename: string;
            /** Local Track Id */
            local_track_id: number | null;
            /** Source Path */
            source_path: string;
        };
        /** UpdateStreamingAccountAuthRequest */
        UpdateStreamingAccountAuthRequest: {
            /** Browser Headers */
            browser_headers: {
                [key: string]: unknown;
            };
        };
        /** UpdateStreamingPlaylistRequest */
        UpdateStreamingPlaylistRequest: {
            /**
             * Sync Mode
             * @enum {string}
             */
            sync_mode: "off" | "match_only" | "full";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_streaming_accounts_api_streaming_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingAccountsResponse"];
                };
            };
        };
    };
    create_streaming_account_api_streaming_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStreamingAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_streaming_playlists_api_streaming_playlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingPlaylistsResponse"];
                };
            };
        };
    };
    list_streaming_playlist_config_api_streaming_playlists_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingPlaylistConfigListResponse"];
                };
            };
        };
    };
    update_streaming_playlist_api_streaming_playlists__playlist_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStreamingPlaylistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingPlaylistConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playlist_detail_api_playlists__playlist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_playlist_tracks_api_playlists__playlist_id__tracks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistTracksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_playlist_m3u_api_playlists__playlist_id__m3u_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_streaming_account_auth_api_streaming_accounts__account_id__auth_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStreamingAccountAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_streaming_account_api_streaming_accounts__account_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_streaming_account_metadata_api_streaming_accounts__account_id__refresh_metadata_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_streaming_playlist_api_streaming_playlists__playlist_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rematch_local_track_api_local_tracks__local_track_id__rematch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                local_track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescue_local_track_metadata_api_local_tracks__local_track_id__rescue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                local_track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_library_tracks_api_library_tracks_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryTracksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_missing_locally_api_maintenance_missing_locally_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingLocallyResponse"];
                };
            };
        };
    };
    list_unidentified_api_maintenance_unidentified_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidentifiedResponse"];
                };
            };
        };
    };
    list_proposals_api_proposals_get: {
        parameters: {
            query?: {
                band?: components["schemas"]["ConfidenceBand"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_proposal_api_proposals__proposal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_api_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    break_final_link_api_final_links__final_link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                final_link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_local_track_detail_api_local_tracks__local_track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                local_track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalTrackDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_general_settings_api_settings_general_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneralSettingsResponse"];
                };
            };
        };
    };
    create_ingest_folder_api_settings_ingest_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIngestFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestFolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ingest_folder_api_settings_ingest_folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
