"""Streaming domain package."""

from app.streaming.jobs import (
    run_youtube_music_playlist_metadata_refresh_job,
    run_youtube_music_playlist_sync_job,
    run_youtube_music_sync_job,
)
from app.streaming.models import (
    PlaylistMembershipRecord,
    PersistedStreamingAccount,
    StoredStreamingAccount,
    StreamingAccountRecord,
    StreamingPlaylistDetail,
    StreamingPlaylistRecord,
    StreamingPlaylistSummary,
    StreamingPlaylistTrack,
    StreamingTrackRecord,
    STREAMING_ACCOUNT_AUTH_STATE_CONNECTED,
    STREAMING_ACCOUNT_AUTH_STATE_ERROR,
    YOUTUBE_MUSIC_PROVIDER,
    metadata,
    playlist_membership_table,
    streaming_accounts_table,
    streaming_playlists_table,
    streaming_tracks_table,
)
from app.streaming.router import create_router
from app.streaming.schemas import (
    CreateStreamingAccountRequest,
    PlaylistDetail,
    PlaylistDetailResponse,
    PlaylistSyncResponse,
    PlaylistTrackResponse,
    PlaylistTracksResponse,
    StreamingAccountResponse,
    StreamingPlaylistConfigResponse,
    StreamingPlaylistResponse,
    StreamingSyncResponse,
    UpdateStreamingPlaylistRequest,
)
from app.streaming.store import StreamingAccountStore

__all__ = [
    "PlaylistMembershipRecord",
    "PersistedStreamingAccount",
    "StoredStreamingAccount",
    "StreamingAccountRecord",
    "StreamingAccountStore",
    "StreamingPlaylistDetail",
    "StreamingPlaylistRecord",
    "StreamingPlaylistSummary",
    "StreamingPlaylistTrack",
    "StreamingTrackRecord",
    "STREAMING_ACCOUNT_AUTH_STATE_CONNECTED",
    "STREAMING_ACCOUNT_AUTH_STATE_ERROR",
    "CreateStreamingAccountRequest",
    "PlaylistDetail",
    "PlaylistDetailResponse",
    "PlaylistSyncResponse",
    "PlaylistTrackResponse",
    "PlaylistTracksResponse",
    "StreamingAccountResponse",
    "StreamingPlaylistConfigResponse",
    "StreamingPlaylistResponse",
    "YOUTUBE_MUSIC_PROVIDER",
    "StreamingSyncResponse",
    "UpdateStreamingPlaylistRequest",
    "create_router",
    "metadata",
    "playlist_membership_table",
    "run_youtube_music_playlist_metadata_refresh_job",
    "run_youtube_music_playlist_sync_job",
    "run_youtube_music_sync_job",
    "streaming_accounts_table",
    "streaming_playlists_table",
    "streaming_tracks_table",
]
