"""Streaming relationship persistence models."""

from app.relationships.suggestions import (
    ACTIVE_RELATIONSHIP_SUGGESTION_PLAYLIST_MODES,
    GeneratedStreamingRelationshipSuggestion,
    MATCH_METHOD_ISRC,
    MATCH_METHOD_TAGS,
    StreamingRelationshipSuggestionGenerationResult,
    StreamingRelationshipSuggestionGenerator,
)
from app.relationships.resolver import (
    EquivalentAcceptanceConflict,
    RelationshipFinalLink,
    RESOLUTION_SOURCE_DIRECT,
    RESOLUTION_SOURCE_EQUIVALENT,
    ResolvedStreamingTrackLink,
    ResolutionSource,
    StreamingRelationshipResolver,
)
from app.relationships.models import (
    NormalizedStreamingTrackPair,
    STREAMING_RELATIONSHIP_CONFIDENCE_HIGH,
    STREAMING_RELATIONSHIP_CONFIDENCE_LOW,
    STREAMING_RELATIONSHIP_CONFIDENCE_MEDIUM,
    STREAMING_RELATIONSHIP_CONFIDENCES,
    STREAMING_RELATIONSHIP_SUGGESTION_STATUS_ACCEPTED,
    STREAMING_RELATIONSHIP_SUGGESTION_STATUS_PENDING,
    STREAMING_RELATIONSHIP_SUGGESTION_STATUS_REJECTED,
    STREAMING_RELATIONSHIP_SUGGESTION_STATUSES,
    STREAMING_RELATIONSHIP_TYPE_EQUIVALENT,
    STREAMING_RELATIONSHIP_TYPE_RELATED,
    STREAMING_RELATIONSHIP_TYPES,
    metadata,
    normalize_streaming_track_pair,
    streaming_relationship_suggestions_table,
    streaming_relationships_table,
)

__all__ = [
    "EquivalentAcceptanceConflict",
    "ACTIVE_RELATIONSHIP_SUGGESTION_PLAYLIST_MODES",
    "GeneratedStreamingRelationshipSuggestion",
    "MATCH_METHOD_ISRC",
    "MATCH_METHOD_TAGS",
    "NormalizedStreamingTrackPair",
    "RelationshipFinalLink",
    "RESOLUTION_SOURCE_DIRECT",
    "RESOLUTION_SOURCE_EQUIVALENT",
    "ResolvedStreamingTrackLink",
    "ResolutionSource",
    "STREAMING_RELATIONSHIP_CONFIDENCE_HIGH",
    "STREAMING_RELATIONSHIP_CONFIDENCE_LOW",
    "STREAMING_RELATIONSHIP_CONFIDENCE_MEDIUM",
    "STREAMING_RELATIONSHIP_CONFIDENCES",
    "STREAMING_RELATIONSHIP_SUGGESTION_STATUS_ACCEPTED",
    "STREAMING_RELATIONSHIP_SUGGESTION_STATUS_PENDING",
    "STREAMING_RELATIONSHIP_SUGGESTION_STATUS_REJECTED",
    "STREAMING_RELATIONSHIP_SUGGESTION_STATUSES",
    "STREAMING_RELATIONSHIP_TYPE_EQUIVALENT",
    "STREAMING_RELATIONSHIP_TYPE_RELATED",
    "STREAMING_RELATIONSHIP_TYPES",
    "StreamingRelationshipSuggestionGenerationResult",
    "StreamingRelationshipSuggestionGenerator",
    "StreamingRelationshipResolver",
    "metadata",
    "normalize_streaming_track_pair",
    "streaming_relationship_suggestions_table",
    "streaming_relationships_table",
]
