"""initial schema

Revision ID: 0f693d613d73
Revises:
Create Date: 2026-04-30 22:25:35.755849
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0f693d613d73"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "local_tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("library_root_rel_path", sa.String(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=True),
        sa.Column("beets_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_local_tracks")),
    )
    op.create_table(
        "streaming_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("auth_token_blob", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_streaming_accounts")),
    )
    op.create_table(
        "streaming_tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_track_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("isrc", sa.String(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_streaming_tracks")),
    )
    op.create_table(
        "final_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("local_track_id", sa.Integer(), nullable=False),
        sa.Column("streaming_track_id", sa.Integer(), nullable=False),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["local_track_id"],
            ["local_tracks.id"],
            name=op.f("fk_final_links_local_track_id_local_tracks"),
        ),
        sa.ForeignKeyConstraint(
            ["streaming_track_id"],
            ["streaming_tracks.id"],
            name=op.f("fk_final_links_streaming_track_id_streaming_tracks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_final_links")),
        sa.UniqueConstraint(
            "local_track_id", name=op.f("uq_final_links_local_track_id")
        ),
    )
    op.create_table(
        "streaming_playlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("provider_playlist_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["streaming_accounts.id"],
            name=op.f("fk_streaming_playlists_account_id_streaming_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_streaming_playlists")),
    )
    op.create_table(
        "suggested_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("local_track_id", sa.Integer(), nullable=False),
        sa.Column("streaming_track_id", sa.Integer(), nullable=False),
        sa.Column("match_method", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["local_track_id"],
            ["local_tracks.id"],
            name=op.f("fk_suggested_links_local_track_id_local_tracks"),
        ),
        sa.ForeignKeyConstraint(
            ["streaming_track_id"],
            ["streaming_tracks.id"],
            name=op.f("fk_suggested_links_streaming_track_id_streaming_tracks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suggested_links")),
    )
    op.create_table(
        "playlist_membership",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("streaming_track_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["streaming_playlists.id"],
            name=op.f("fk_playlist_membership_playlist_id_streaming_playlists"),
        ),
        sa.ForeignKeyConstraint(
            ["streaming_track_id"],
            ["streaming_tracks.id"],
            name=op.f("fk_playlist_membership_streaming_track_id_streaming_tracks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist_membership")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_membership")
    op.drop_table("suggested_links")
    op.drop_table("streaming_playlists")
    op.drop_table("final_links")
    op.drop_table("streaming_tracks")
    op.drop_table("streaming_accounts")
    op.drop_table("local_tracks")
    # ### end Alembic commands ###
