"""add beets mirror tables

Revision ID: b9c2f4a8e7d1
Revises: 9b7e3c2d1a4f
Create Date: 2026-05-08 00:00:00.000000
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "b9c2f4a8e7d1"
down_revision = "9b7e3c2d1a4f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "beets_items",
        sa.Column("beets_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("album_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("artist", sa.Text(), nullable=True),
        sa.Column("artists", sa.Text(), nullable=True),
        sa.Column("artists_ids", sa.Text(), nullable=True),
        sa.Column("artist_sort", sa.Text(), nullable=True),
        sa.Column("artists_sort", sa.Text(), nullable=True),
        sa.Column("artist_credit", sa.Text(), nullable=True),
        sa.Column("artists_credit", sa.Text(), nullable=True),
        sa.Column("remixer", sa.Text(), nullable=True),
        sa.Column("album", sa.Text(), nullable=True),
        sa.Column("albumartist", sa.Text(), nullable=True),
        sa.Column("albumartists", sa.Text(), nullable=True),
        sa.Column("albumartist_sort", sa.Text(), nullable=True),
        sa.Column("albumartists_sort", sa.Text(), nullable=True),
        sa.Column("albumartist_credit", sa.Text(), nullable=True),
        sa.Column("albumartists_credit", sa.Text(), nullable=True),
        sa.Column("genre", sa.Text(), nullable=True),
        sa.Column("style", sa.Text(), nullable=True),
        sa.Column("discogs_albumid", sa.Integer(), nullable=True),
        sa.Column("discogs_artistid", sa.Integer(), nullable=True),
        sa.Column("discogs_labelid", sa.Integer(), nullable=True),
        sa.Column("lyricist", sa.Text(), nullable=True),
        sa.Column("composer", sa.Text(), nullable=True),
        sa.Column("composer_sort", sa.Text(), nullable=True),
        sa.Column("work", sa.Text(), nullable=True),
        sa.Column("mb_workid", sa.Text(), nullable=True),
        sa.Column("work_disambig", sa.Text(), nullable=True),
        sa.Column("arranger", sa.Text(), nullable=True),
        sa.Column("grouping", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("day", sa.Integer(), nullable=True),
        sa.Column("track", sa.Integer(), nullable=True),
        sa.Column("tracktotal", sa.Integer(), nullable=True),
        sa.Column("disc", sa.Integer(), nullable=True),
        sa.Column("disctotal", sa.Integer(), nullable=True),
        sa.Column("lyrics", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("bpm", sa.Integer(), nullable=True),
        sa.Column("comp", sa.Boolean(), nullable=True),
        sa.Column("mb_trackid", sa.Text(), nullable=True),
        sa.Column("mb_albumid", sa.Text(), nullable=True),
        sa.Column("mb_artistid", sa.Text(), nullable=True),
        sa.Column("mb_artistids", sa.Text(), nullable=True),
        sa.Column("mb_albumartistid", sa.Text(), nullable=True),
        sa.Column("mb_albumartistids", sa.Text(), nullable=True),
        sa.Column("mb_releasetrackid", sa.Text(), nullable=True),
        sa.Column("trackdisambig", sa.Text(), nullable=True),
        sa.Column("albumtype", sa.Text(), nullable=True),
        sa.Column("albumtypes", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("barcode", sa.Text(), nullable=True),
        sa.Column("acoustid_fingerprint", sa.Text(), nullable=True),
        sa.Column("acoustid_id", sa.Text(), nullable=True),
        sa.Column("mb_releasegroupid", sa.Text(), nullable=True),
        sa.Column("release_group_title", sa.Text(), nullable=True),
        sa.Column("asin", sa.Text(), nullable=True),
        sa.Column("isrc", sa.Text(), nullable=True),
        sa.Column("catalognum", sa.Text(), nullable=True),
        sa.Column("script", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("albumstatus", sa.Text(), nullable=True),
        sa.Column("media", sa.Text(), nullable=True),
        sa.Column("albumdisambig", sa.Text(), nullable=True),
        sa.Column("releasegroupdisambig", sa.Text(), nullable=True),
        sa.Column("disctitle", sa.Text(), nullable=True),
        sa.Column("encoder", sa.Text(), nullable=True),
        sa.Column("rg_track_gain", sa.Float(), nullable=True),
        sa.Column("rg_track_peak", sa.Float(), nullable=True),
        sa.Column("rg_album_gain", sa.Float(), nullable=True),
        sa.Column("rg_album_peak", sa.Float(), nullable=True),
        sa.Column("r128_track_gain", sa.Float(), nullable=True),
        sa.Column("r128_album_gain", sa.Float(), nullable=True),
        sa.Column("original_year", sa.Integer(), nullable=True),
        sa.Column("original_month", sa.Integer(), nullable=True),
        sa.Column("original_day", sa.Integer(), nullable=True),
        sa.Column("initial_key", sa.Text(), nullable=True),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("bitrate_mode", sa.Text(), nullable=True),
        sa.Column("encoder_info", sa.Text(), nullable=True),
        sa.Column("encoder_settings", sa.Text(), nullable=True),
        sa.Column("format", sa.Text(), nullable=True),
        sa.Column("samplerate", sa.Integer(), nullable=True),
        sa.Column("bitdepth", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("mtime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("added", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("beets_id", name=op.f("pk_beets_items")),
    )
    op.create_table(
        "beets_albums",
        sa.Column("beets_album_id", sa.Integer(), nullable=False),
        sa.Column("artpath", sa.Text(), nullable=True),
        sa.Column("added", sa.DateTime(timezone=True), nullable=True),
        sa.Column("albumartist", sa.Text(), nullable=True),
        sa.Column("albumartist_sort", sa.Text(), nullable=True),
        sa.Column("albumartist_credit", sa.Text(), nullable=True),
        sa.Column("albumartists", sa.Text(), nullable=True),
        sa.Column("albumartists_sort", sa.Text(), nullable=True),
        sa.Column("albumartists_credit", sa.Text(), nullable=True),
        sa.Column("album", sa.Text(), nullable=True),
        sa.Column("genre", sa.Text(), nullable=True),
        sa.Column("style", sa.Text(), nullable=True),
        sa.Column("discogs_albumid", sa.Integer(), nullable=True),
        sa.Column("discogs_artistid", sa.Integer(), nullable=True),
        sa.Column("discogs_labelid", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("day", sa.Integer(), nullable=True),
        sa.Column("disctotal", sa.Integer(), nullable=True),
        sa.Column("comp", sa.Boolean(), nullable=True),
        sa.Column("mb_albumid", sa.Text(), nullable=True),
        sa.Column("mb_albumartistid", sa.Text(), nullable=True),
        sa.Column("albumtype", sa.Text(), nullable=True),
        sa.Column("albumtypes", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("barcode", sa.Text(), nullable=True),
        sa.Column("mb_releasegroupid", sa.Text(), nullable=True),
        sa.Column("release_group_title", sa.Text(), nullable=True),
        sa.Column("asin", sa.Text(), nullable=True),
        sa.Column("catalognum", sa.Text(), nullable=True),
        sa.Column("script", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("albumstatus", sa.Text(), nullable=True),
        sa.Column("albumdisambig", sa.Text(), nullable=True),
        sa.Column("releasegroupdisambig", sa.Text(), nullable=True),
        sa.Column("rg_album_gain", sa.Float(), nullable=True),
        sa.Column("rg_album_peak", sa.Float(), nullable=True),
        sa.Column("r128_album_gain", sa.Float(), nullable=True),
        sa.Column("original_year", sa.Integer(), nullable=True),
        sa.Column("original_month", sa.Integer(), nullable=True),
        sa.Column("original_day", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("beets_album_id", name=op.f("pk_beets_albums")),
    )
    op.create_table(
        "beets_item_attributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["beets_items.beets_id"],
            name=op.f("fk_beets_item_attributes_entity_id_beets_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_beets_item_attributes")),
        sa.UniqueConstraint(
            "entity_id",
            "key",
            name=op.f("uq_beets_item_attributes_entity_id"),
        ),
    )
    op.create_table(
        "beets_album_attributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["beets_albums.beets_album_id"],
            name=op.f("fk_beets_album_attributes_entity_id_beets_albums"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_beets_album_attributes")),
        sa.UniqueConstraint(
            "entity_id",
            "key",
            name=op.f("uq_beets_album_attributes_entity_id"),
        ),
    )


def downgrade() -> None:
    op.drop_table("beets_album_attributes")
    op.drop_table("beets_item_attributes")
    op.drop_table("beets_albums")
    op.drop_table("beets_items")
